/* Auto-generated by scripts/build-kitchen-vault.js — safe to host on GitHub Pages.
 * Portal key is encrypted per staff password. Rebuild after changing passwords.
 */
window.BB_KITCHEN_VAULT = {
  "v": 1,
  "app": "bobs-kitchen",
  "users": [
    {
      "email": "bobsburritosco@gmail.com",
      "salt": "MCno8Df/YwjH6W2FoT9Cjg==",
      "iv": "HDW0W7DfDhEVoGPI",
      "tag": "7UmBCB7qD10GPZxc6OtE5g==",
      "data": "vYyK9nuhkGrxz5eQvl4Lec2Mtp5JBU8nYMx7jvoT6u5ZR/GJ6vWgy+0DUgNwfJdOavdOHFF8OFdOTd7Txzrw4FFprXDvuwtj9KhFohTK/izfVCKp4Gx8MRPIhtn6v37iQ3DqIoD8QOU+5xgltkFN7vc8+IptUId0HvFOMQ7ZN8f/fN3p6HrtONEMG6h8QYkoLlD7kGiLl4rHowhYi8n75tR0IEmphQ+ilruSsXgdzok2nAHnGjnhOo35tm7oiUs="
    },
    {
      "email": "migueldiezaznar@gmail.com",
      "salt": "5rgDOX1BRmBtAAwIhF4Xyg==",
      "iv": "QNXaU8vUw2fqnLcn",
      "tag": "40DLAm+j9sHkr06YV81VAg==",
      "data": "qYs8MONbr6O3nnCN4Wnamc2P3Hk7hRTgMd9S2euEgaOPUvoFvfJwnyGukk5MeSo3LFWirwMBDp2Fh5wYUnUHzpd14FWBLtBE/9i/p6Q4Ns80liJKbrPkZhUEvJHSSb5fEiCsOraMA5aQmWfjxdhB35WTnf0Y8X5GzX9tOI/loizOY5f/D5FXC9Jxj++aq2/ivQUUwcdMZ1ZsKQb+oso2rVTQoGiA8kAGyY3Z+W4yKtGtYQh8uPocAwZcMxLr5m0="
    }
  ]
};
